# Load any supplementary scripts
for config in "$HOME"/.profile.d/*.sh ; do
    . "$config"
done
unset -v config

# Source interactive Bash config if it exists
if [[ -e $HOME/.bashrc ]] ; then
    source "$HOME"/.bashrc
fi
