# .bashrc

# Add ~/.local/bin to PATH if it exists
if [ -d "$HOME"/.local/bin ] ; then
    PATH=$HOME/.local/bin:$PATH
fi

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# Load any supplementary scripts
for config in "$HOME"/.bashrc.d/*.bash ; do
        source "$config"
done
unset -v config
