# Load ~/.profile regardless of shell version
if [ -e "$HOME"/.profile ] ; then
    . "$HOME"/.profile
fi

# Load any supplementary scripts
if [[ -d $HOME/.bash_profile.d ]] ; then
    for bash_profile in "$HOME"/.bash_profile.d/*.bash ; do
        if [[ -e $bash_profile ]] ; then
            source "$bash_profile"
        fi
    done
    unset -v bash_profile
fi

# Source interactive Bash config if it exists
if [[ -e $HOME/.bashrc ]] ; then
    source "$HOME"/.bashrc
fi
